In [67]:
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, 
    precision_recall_fscore_support,
    confusion_matrix, classification_report,     
)

In [1]:
#!/usr/bin/python

"""
    Starter code for the validation mini-project.
    The first step toward building your POI identifier!

    Start by loading/formatting the data

    After that, it's not our code anymore--it's yours!
"""

import pickle
import sys
sys.path.append("../tools/")
from feature_format import featureFormat, targetFeatureSplit

data_dict = pickle.load(open("../final_project/final_project_dataset.pkl", "r") )

### first element is our labels, any added elements are predictor
### features. Keep this the same for the mini-project, but you'll
### have a different feature list when you do the final project.
features_list = ["poi", "salary"]

# Python 3
# data = featureFormat(data_dict, features_list)

# Python 2.7
data = featureFormat(data_dict, features_list, sort_keys = '../tools/python2_lesson13_keys.pkl')

labels, features = targetFeatureSplit(data)

In [2]:
len(features)

95

In [3]:
features[:2]

[array([ 365788.]), array([ 267102.])]

In [4]:
labels[:2]

[0.0, 0.0]

In [5]:
### it's all yours from here forward!  
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(features, labels)
print clf.score(features, labels)

0.989473684211


In [6]:
clf.feature_importances_

array([ 1.])

In [7]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.3, random_state=42)

In [15]:
type(features_train)

list

In [8]:
len(features_train)

66

In [9]:
features_train[:2]

[array([ 26704229.]), array([ 248546.])]

In [59]:
len(labels_train)

66

In [61]:
sum(labels_train)  # so the labels have imbalanced classes

13.0

In [62]:
13.0/66

0.19696969696969696

In [63]:
len(labels_test)

29

In [64]:
sum(labels_test)

4.0

In [65]:
4.0/29

0.13793103448275862

In [10]:
clf.fit(features_train, labels_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [11]:
clf.score(features_test, labels_test)

0.72413793103448276

In [37]:
pred = clf.predict(features_test)
pred

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [40]:
sum(pred == 1)

4

In [34]:
len(labels_test)

29

In [41]:
labels_test_np = np.array(labels_test)
sum(np.array(labels_test) == 1)

4

In [33]:
sum(np.array(labels_train) == 1)

13

In [35]:
25.0/29

0.8620689655172413

In [42]:
labels_test_np

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,
        0.,  1.,  0.])

In [43]:
pred

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [52]:
pred == 1

array([False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False], dtype=bool)

In [53]:
labels_test_np == 1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False,  True,  True, False,
        True, False], dtype=bool)

In [77]:
sum((pred == 1) & (labels_test_np == 1))

0

In [47]:
confusion_matrix(labels_test, pred)

array([[21,  4],
       [ 4,  0]])

In [50]:
print classification_report(labels_test, pred)

             precision    recall  f1-score   support

        0.0       0.84      0.84      0.84        25
        1.0       0.00      0.00      0.00         4

avg / total       0.72      0.72      0.72        29



In [68]:
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, 
    precision_recall_fscore_support,
    confusion_matrix, classification_report,     
)

In [70]:
accuracy_score(labels_test, pred)

0.72413793103448276

In [71]:
precision_score(labels_test, pred)

0.0

In [72]:
recall_score(labels_test, pred)

0.0

In [74]:
precision_recall_fscore_support(labels_test, pred)

(array([ 0.84,  0.  ]),
 array([ 0.84,  0.  ]),
 array([ 0.84,  0.  ]),
 array([25,  4]))

In [76]:
predictions = [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1]
true_labels = [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]

In [80]:
sum((np.array(predictions) == 1) & (np.array(true_labels) == 1))

6

In [81]:
sum((np.array(predictions) == 0) & (np.array(true_labels) == 0))

9

In [82]:
sum((np.array(predictions) == 1) & (np.array(true_labels) == 0))

3

In [83]:
sum((np.array(predictions) == 0) & (np.array(true_labels) == 1))

2

In [84]:
0.67 * 0.75 / (0.67 + 0.75)

0.3538732394366198